Class = require('src/utils/class')
require('src/utils/utils')
require('src/utils/stateMachine')
require('src/utils/baseState')
require('src/scenes/mainMenuState')
require('src/scenes/firstLevelState')